### ISSUE TITLE
New tooltip appear each time render is triggered

### ISSUE THREAD

**Issue by StevenMasini** [prscX/react-native-tooltips#10]
Hi Pranav, me again ^^

Actually the first time I integrated the library into my project, I noticed that a new tooltip will be created and display each time the render method of my container is triggered.

In order to avoid this issue I had to change the class extended by RNTooltip from `Component` to `PureComponent`.

`PureComponent` will perform a shallow compare into `shouldComponentUpdate` method in order to reduce the amount of useless re-render.

This is an easy fix, I can submit a Pull Request for this if you want ?

**Comment by prscX** [comment]
Thanks @StevenMasini for the effort and sharing the solution.

I believe shared solution is the best approach in order to fix this issue. Please share a PR for the same.

Thanks
</ Pranav >

**Comment by StevenMasini** [comment]
#11

**Comment by prscX** [comment]
Thanks @StevenMasini for the effort and PR.

I have merged and released a build with the same. Can you please install and verify the same.

Thanks
</ Pranav >

**Comment by StevenMasini** [comment]
Well it wasn't much, but I am glad I could help ^^
