### ISSUE TITLE
[Android] Missing build tool version

### ISSUE THREAD

**Issue by congnguyen91** [prscX/react-native-tooltips#2]
A problem occurred configuring project ':react-native-tooltips'.
      > buildToolsVersion is not specified.

**Comment by prscX** [comment]
Thanks @congnguyen91 for raising the issue.

I have added `buildToolsVersion` and released it with v0.0.3. Can you please download the latest version and verify the same.

Let me know in case you still face the same issue.

Thanks
Pranav
