### ISSUE TITLE
Any way to create tooltips without arrows?

### ISSUE THREAD

**Issue by halileohalilei** [prscX/react-native-tooltips#3]
I need to have a couple of tooltips in my project, and one of them is a tooltip without any arrows. I can manage it by creating a custom View of my own, but I want to use the same library for my tooltips. Is there any way I can achieve this? 

Also, when I was writing pure native iOS, I used to use https://github.com/teodorpatras/EasyTipView which was super easy to use and easily customizable. Any chance react-native-tooltips can switch to that on the iOS side?

Either way, thanks for the package!

**Comment by prscX** [comment]
Thanks @halileohalilei for raising the query.

- My initial plan was to integrate [EasyTipView](https://github.com/teodorpatras/EasyTipView), but while doing so I faced multiple issues and the tooltip was not displaying. Then I came across [SexyTooltip](https://github.com/calm/SexyTooltip) which seems to be promising.

- I have added `arrow={true/false}` prop through which you can add/remove the arrow. Currently it is supported only on iOS, for Android I have raised the issue to [ViewTooltip: 31](https://github.com/florent37/ViewTooltip/issues/31). Based on their response I will impl the same prop for Android as well.

- Once it is enabled on Android, I will publish the next release with the same. Meantime in case you want to use it for iOS please use master branch.

Thanks
Pranav

**Comment by prscX** [comment]
Hi @halileohalilei,

Updates: `Android: ViewTooltip` has add API to set arrow height and width. Coming weekend I will integrate the same in our library and will push the release version.

Thanks
Pranav

**Comment by prscX** [comment]
Hi @halileohalilei, I have enabled arrow customisation on Android as well. Please find below screenshot of the same:

<img width="161" alt="screen shot 2018-03-08 at 6 01 26 am" src="https://user-images.githubusercontent.com/28862892/37126490-45eb14c6-2297-11e8-8b2b-16e2ab17f12d.png">
  
However I am not able to set padding between button and tooltip, I have requested help from ViewTooltip Team, post these fix's I will release the latest version.

Thanks
Pranav

**Comment by prscX** [comment]
Hi @halileohalilei,

I have release latest `V0.0.4` with prop enabling/disabling arrow. Can you please download the latest version and verify the same.

Let me know in case you face any issues.

Thanks
Pranav

**Comment by halileohalilei** [comment]
@prscX you are the best! I decided to go with a simple approach for now, but I will be integrating tooltips to my app in a few weeks. I will let you know if I stumble upon any problems. Cheers!

**Comment by prscX** [comment]
Sure @halileohalilei. Please feel free to raise issue/gaps if you find any.

Thanks
Pranav
