### ISSUE TITLE
Remove pod install from postinstall script

### ISSUE THREAD

**Issue by tbergq** [prscX/react-native-tooltips#4]
Hi, I would like to use this tooltip, but it crashes our CI, since it does not have pod installed (linux).

Would it be possible to remove `pod install` from the postinstall script?

**Comment by prscX** [comment]
Thanks @tbergq for showing interest and raising the issue.

I was giving thought to remove `postinstall` script and to have manual installation steps. Please give me some time I will fix this in coming weekend.

Meantime can you please fork this library and remove the `postinstall` script for the usage.

Thanks
Pranav

**Comment by prscX** [comment]
Hi @tbergq, I have removed `postinstall` from `package.json`. 

**MAC**: Now onwards we have to manually install iOS library pods using below command:

`$ cd ./node_modules/react-native-tooltips/ios && pod install`

Now it should work on your linux machine, can you please download the latest V0.0.4 and verify the same. Let me know in case you still face any issue.

Thanks
Pranav

**Comment by tbergq** [comment]
Thank you, I can confirm that it works for us now.

**Comment by kaushikwavhal** [comment]
@prscX my machine gets stuck at the pod install as it's still there as a postinstall script in the package.json.

**Comment by prscX** [comment]
@kaushikwavhal: Can you please share the version of this library you are using.

Thanks
</ Pranav >

**Comment by kaushikwavhal** [comment]
@prscX I just downloaded the latest version through npm.
