### ISSUE TITLE
Incorrect code?

### ISSUE THREAD

**Issue by aMarCruz** [prscX/react-native-tooltips#6]
@prscX , thanks for your great work.

Looking at the JS code I see this block stating at [line 72](https://github.com/prscX/react-native-tooltips/blob/master/RNTooltips.js#L72) of RNTooltips.js:
```js
    if (props.text === undefined) {
      props.text = Tooltips.defaultProps.text;
    } else if (props.position === undefined) {
      props.position = Tooltips.defaultProps.position;
    } else if (props.align === undefined) {
       // . . . etc
```

If the intention is to test each value, the correct code would be:
```js
    if (props.text === undefined) {
      props.text = Tooltips.defaultProps.text;
    }
    if (props.position === undefined) {
      props.position = Tooltips.defaultProps.position;
    }
    if (props.align === undefined) {
       // . . . etc
```

...otherwise the chain will break with the first equality, ex. if both `position` and `align` are undefined, only `position` will get the default.

In the other hand, React and React native already [sets automatically default values](https://reactjs.org/docs/typechecking-with-proptypes.html#default-prop-values) with the static `Tooltips.defaultProps` property, so ~~these block _is not necessary_~~ (EDIT: sorry, Show is static as well).

**Comment by prscX** [comment]
Thanks a lot @aMarCruz for pointing out the issue.

Completely my bad. Please let me know in case you are looking to raise a PR else I can do the required changes in order fix it.

Thanks
</ Pranav >

**Comment by aMarCruz** [comment]
@prscX , just now I'm working in a local fork of your repo, fixing a strange issue with the Android API.
I need to finish my current project this week, but after that I will gladly contribute fixing this new issue. Thanks

**Comment by prscX** [comment]
Hi @aMarCruz: While fixing [ISSUE: 9](https://github.com/prscX/react-native-tooltips/issues/9), I have fixed this as well.

Thanks for sharing the issue.

Thanks
</ Pranav >
