### ISSUE TITLE
Can't dismiss tooltip using visible = false

### ISSUE THREAD

**Issue by StevenMasini** [prscX/react-native-tooltips#9]
Hi Pranav,

I found out that you can't use the props `visible` to dismiss the tooltips.
Actually you forgot to mention the `dismiss` props in your documentation. That's the one that should be used to dismiss the tooltips.

But also while `dismiss` must be equal to `true`, the `visible` props must also be equal to `true`.

```
componentDidUpdate() {
    if (this.props.visible && this.props.reference) {
      if (this.props.dismiss) {
        Tooltips.Dismiss(findNodeHandle(this.props.reference));
      } else {
        Tooltips.Show(findNodeHandle(this.props.reference), {
          text: this.props.text,
          position: this.props.position,
          align: this.props.align,
...
```

I think we should mention in the documentation, explain how to dismiss the tooltip.

**Comment by prscX** [comment]
Thanks @StevenMasini for raising the issue.

I have fixed and pushed a release with the same. Can you please install/download latest version of library.

Please let me know incase you still face the same issue.

Thanks
</ Pranav >

**Comment by StevenMasini** [comment]
I saw the fix, thanks 👍
